"use client";

import { useMemo, useState, type CSSProperties } from "react";

type NodeStatus =
  | "LMS theorem"
  | "proved extension"
  | "algorithm"
  | "diagnostic"
  | "bridge";

type IdeaNode = {
  id: string;
  label: string;
  short: string;
  formula?: string;
  status: NodeStatus;
  source: string;
  x: number;
  y: number;
  w: number;
  h: number;
};

type Cluster = {
  id: string;
  title: string;
  subtitle: string;
  thesis: string;
  accent: string;
  x: number;
  y: number;
  w: number;
  h: number;
  nodes: IdeaNode[];
};

type RelationKind =
  | "foundation"
  | "exact"
  | "algorithm"
  | "invariant"
  | "bridge";

type Edge = {
  from: string;
  to: string;
  label: string;
  kind: RelationKind;
};

type GraphNode = IdeaNode & {
  clusterId: string;
  clusterTitle: string;
  absX: number;
  absY: number;
};

const clusters: Cluster[] = [
  {
    id: "lms",
    title: "LMS hyperbolic engine",
    subtitle: "What the original LMS paper proves and supplies",
    thesis:
      "Identical-A Kuramoto-on-sphere dynamics are generated by the Mobius isometry group of the Poincare ball. Linear mean-field coupling makes the boost coordinate a hyperbolic gradient flow.",
    accent: "#2563eb",
    x: 70,
    y: 70,
    w: 500,
    h: 380,
    nodes: [
      {
        id: "sphere-flow",
        label: "Sphere dynamics",
        short:
          "Particles stay on S^{d-1}; the common A and common field Z define a conformal infinitesimal generator.",
        formula: "dot x_i = x_i A^T + Z - <Z,x_i>x_i",
        status: "LMS theorem",
        source: "LMS.tex, Preliminaries",
        x: 22,
        y: 68,
        w: 210,
        h: 72,
      },
      {
        id: "mobius-boosts",
        label: "Mobius boosts M_w",
        short:
          "Boosts M_w are ball isometries, preserve the sphere boundary, and satisfy M_w^{-1}=M_{-w}.",
        formula: "M_w(x)=((1-|w|^2)(x-w))/|x-w|^2 - w",
        status: "LMS theorem",
        source: "LMS.tex, Hyperbolic geometry",
        x: 260,
        y: 68,
        w: 210,
        h: 72,
      },
      {
        id: "group-orbit",
        label: "Finite Mobius orbit",
        short:
          "For generic base cloud p, the full N-body state remains on Gp with parameters (w,zeta).",
        formula: "x_i = M_w(p_i) zeta^T",
        status: "LMS theorem",
        source: "LMS.tex, Reduced equations",
        x: 22,
        y: 170,
        w: 210,
        h: 72,
      },
      {
        id: "reduced-odes",
        label: "Reduced ODEs",
        short:
          "The high-dimensional particle flow closes on boost and rotation coordinates.",
        formula:
          "dot w = -1/2(1-|w|^2) zeta^{-1}Z; dot zeta=(A-alpha(zeta w,Z))zeta",
        status: "LMS theorem",
        source: "LMS.tex, Reduced equations",
        x: 260,
        y: 170,
        w: 210,
        h: 72,
      },
      {
        id: "linear-decoupling",
        label: "Linear mean-field decoupling",
        short:
          "For Z=sum_i a_i x_i, the w equation depends only on p and w; zeta drops out.",
        formula: "dot w = -1/2(1-|w|^2) Z(M_w(p))",
        status: "LMS theorem",
        source: "LMS.tex, Z versus W coordinates",
        x: 22,
        y: 272,
        w: 210,
        h: 72,
      },
      {
        id: "lms-potential",
        label: "Busemann potential",
        short:
          "The decoupled w vector field is the negative hyperbolic gradient of a weighted Busemann potential.",
        formula: "Phi_p(w)=sum_i a_i log((1-|w|^2)/|w-p_i|^2)",
        status: "LMS theorem",
        source: "LMS.tex, Gradient system",
        x: 260,
        y: 272,
        w: 210,
        h: 72,
      },
    ],
  },
  {
    id: "inverse",
    title: "Canonical inverse and boost gauge",
    subtitle: "The cloud itself becomes the boundary data",
    thesis:
      "The reduced center is not an observable until a gauge is chosen. Exact Busemann inversion fixes the boost gauge by selecting the unique deboost that centers the weighted cloud.",
    accent: "#0f766e",
    x: 690,
    y: 50,
    w: 540,
    h: 440,
    nodes: [
      {
        id: "gauge-dependence",
        label: "w is a coordinate",
        short:
          "Changing the base representative p changes w by the same Mobius action; w is not a raw statistic.",
        formula: "p'=M(p) implies w'=M(w)",
        status: "proved extension",
        source: "Exact inversion note, Prop. 1",
        x: 24,
        y: 72,
        w: 220,
        h: 72,
      },
      {
        id: "centered-slice",
        label: "Centered slice S_0",
        short:
          "The zero-barycenter condition removes boost freedom while leaving rotations as residual gauge.",
        formula: "S_0={p: sum_i a_i p_i=0}",
        status: "proved extension",
        source: "Gauge invariants draft, Sec. 3",
        x: 288,
        y: 72,
        w: 220,
        h: 72,
      },
      {
        id: "empirical-cloud",
        label: "Observed empirical measure",
        short:
          "The finite cloud x with weights a_i is used directly, not compressed to its centroid.",
        formula: "mu_N=sum_i a_i delta_{x_i}",
        status: "proved extension",
        source: "Exact inversion note, Sec. 2",
        x: 24,
        y: 176,
        w: 220,
        h: 72,
      },
      {
        id: "residual-equation",
        label: "Exact residual",
        short:
          "The inverse center v is the deboost parameter whose transformed cloud has zero weighted barycenter.",
        formula: "R_x(v)=sum_i a_i M_v(x_i)=0",
        status: "proved extension",
        source: "Exact inversion note, Def. 2",
        x: 288,
        y: 176,
        w: 220,
        h: 72,
      },
      {
        id: "cloud-potential",
        label: "Cloud Busemann objective",
        short:
          "Apply the LMS potential formula with the observed cloud as anchor data.",
        formula: "Phi_x(v)=sum_i a_i log((1-|v|^2)/|v-x_i|^2)",
        status: "proved extension",
        source: "Exact inversion note, Secs. 5-6",
        x: 24,
        y: 280,
        w: 220,
        h: 72,
      },
      {
        id: "unique-center",
        label: "Unique maximizer",
        short:
          "Under positive weights, no majority mass, and generic anchors, the exact residual has one solution.",
        formula: "max_i a_i < 1/2 => unique v_* in B^d",
        status: "proved extension",
        source: "Exact inversion note, Theorem 6",
        x: 288,
        y: 280,
        w: 220,
        h: 72,
      },
      {
        id: "mobius-equivariance",
        label: "Mobius equivariance",
        short:
          "The canonical center transforms naturally under ambient hyperbolic isometries.",
        formula: "v_*(gx)=g(v_*(x))",
        status: "proved extension",
        source: "Exact inversion note, Theorem 7",
        x: 156,
        y: 366,
        w: 220,
        h: 52,
      },
    ],
  },
  {
    id: "construction",
    title: "Exact state construction",
    subtitle: "From a raw cloud to reduced LMS initial data",
    thesis:
      "Busemann inversion supplies the canonical base cloud. Radius control is a separate exact orbit placement, not a deformation of the inverse solve.",
    accent: "#c2410c",
    x: 1320,
    y: 70,
    w: 500,
    h: 400,
    nodes: [
      {
        id: "sign-clean",
        label: "Sign-clean variables",
        short:
          "Use v=-w to solve the centering equation, then return to LMS reduced coordinates.",
        formula: "z=v_*, w_*=-v_*",
        status: "proved extension",
        source: "Exact inversion note, Sec. 4",
        x: 24,
        y: 72,
        w: 210,
        h: 72,
      },
      {
        id: "deboosted-base",
        label: "Deboosted base cloud",
        short:
          "The exact base representative is obtained by applying the inverse-center boost to every observed point.",
        formula: "p_i=M_{v_*}(x_i)=M_{-w_*}(x_i)",
        status: "proved extension",
        source: "Exact inversion note, Cor. 10",
        x: 260,
        y: 72,
        w: 210,
        h: 72,
      },
      {
        id: "rapidity-solver",
        label: "Rapidity solver",
        short:
          "Optimize in unconstrained rapidity coordinates so iterates remain inside B^d.",
        formula: "v(y)=tanh(|y|) y/|y|",
        status: "algorithm",
        source: "Exact inversion note, Algorithm 9",
        x: 24,
        y: 174,
        w: 210,
        h: 72,
      },
      {
        id: "local-initializer",
        label: "Finite-N initializer",
        short:
          "The first two empirical moments give a small-center Newton seed.",
        formula: "v^(0)=1/2 (I-C+lambda I)^{-1} mu",
        status: "algorithm",
        source: "Exact inversion note, Prop. 8",
        x: 260,
        y: 174,
        w: 210,
        h: 72,
      },
      {
        id: "orbit-projection",
        label: "Exact orbit projection",
        short:
          "To impose a target radius/direction, keep p fixed and select a new point on the same Mobius orbit.",
        formula: "x_i^target=M_{w_target}(p_i)",
        status: "algorithm",
        source: "Exact inversion note, Theorem 11",
        x: 24,
        y: 276,
        w: 210,
        h: 72,
      },
      {
        id: "finite-reconstruction",
        label: "Finite-N reconstruction",
        short:
          "Store p_i once, evolve only (w,zeta), and reconstruct all N particles exactly.",
        formula: "x_i(t)=M_{w(t)}(p_i^0) zeta(t)^T",
        status: "algorithm",
        source: "Gauge invariants draft, Sec. 5",
        x: 260,
        y: 276,
        w: 210,
        h: 72,
      },
    ],
  },
  {
    id: "invariants",
    title: "Moving-frame invariants",
    subtitle: "What survives after the boost gauge is removed",
    thesis:
      "Canonical centering converts the LMS orbit into pure rotation of a centered shape. All rotational invariants of that shape are conserved.",
    accent: "#9333ea",
    x: 250,
    y: 560,
    w: 560,
    h: 440,
    nodes: [
      {
        id: "moving-frame",
        label: "Moving centered frame",
        short:
          "At each time, deboost by z(t) to obtain the canonical centered representative.",
        formula: "p_i^*(t)=M_{z(t)}(x_i(t))",
        status: "proved extension",
        source: "Gauge invariants draft, Sec. 6",
        x: 24,
        y: 72,
        w: 230,
        h: 72,
      },
      {
        id: "covariant-constant",
        label: "Covariantly constant shape",
        short:
          "The centered cloud is just the frozen base cloud transported by the rotation zeta(t).",
        formula: "p_i^*(t)=p_i^0 zeta(t)^T",
        status: "proved extension",
        source: "Gauge invariants draft, Sec. 6",
        x: 302,
        y: 72,
        w: 230,
        h: 72,
      },
      {
        id: "gram-invariants",
        label: "Gram invariants",
        short:
          "All pairwise inner products of the centered cloud are conserved.",
        formula: "G_ij(t)=<p_i^*(t),p_j^*(t)>",
        status: "proved extension",
        source: "Gauge invariants draft, Sec. 7",
        x: 24,
        y: 176,
        w: 230,
        h: 72,
      },
      {
        id: "moment-invariants",
        label: "Moment spectra",
        short:
          "Weighted inertia and higher moment tensors rotate covariantly, so spectra and contractions are invariants.",
        formula: "T=sum_i a_i p_i^{*T}p_i^*",
        status: "proved extension",
        source: "Gauge invariants draft, Sec. 7",
        x: 302,
        y: 176,
        w: 230,
        h: 72,
      },
      {
        id: "connection",
        label: "Connection term",
        short:
          "The changing boost frame induces a rotational connection, the higher-dimensional Thomas-precession term.",
        formula: "Omega=A+alpha(z,Z)",
        status: "proved extension",
        source: "Gauge invariants draft, Sec. 8",
        x: 24,
        y: 280,
        w: 230,
        h: 72,
      },
      {
        id: "data-diagnostics",
        label: "Data diagnostics",
        short:
          "Estimate Omega from centered trajectory data; symmetric strain should vanish for exact LMS motion.",
        formula: "C=Omega T; skew(CT^+) vs A+alpha(z,Z)",
        status: "diagnostic",
        source: "Gauge invariants draft, Sec. 9",
        x: 302,
        y: 280,
        w: 230,
        h: 72,
      },
      {
        id: "local-source",
        label: "Local source exponents",
        short:
          "The linearized boost instability at the centered representative is determined by the inertia tensor.",
        formula: "dot u = u(I-T)+O(|u|^2)",
        status: "diagnostic",
        source: "Gauge invariants draft, Sec. 10",
        x: 24,
        y: 366,
        w: 230,
        h: 52,
      },
      {
        id: "euler-sundman",
        label: "Euler-Sundman lift",
        short:
          "A time reparametrization turns the hyperbolic gradient branch into a Euclidean gradient diagnostic.",
        formula: "dw/dtau=-grad_euc Phi_P(w)",
        status: "diagnostic",
        source: "Gauge invariants draft, Sec. 11",
        x: 302,
        y: 366,
        w: 230,
        h: 52,
      },
    ],
  },
  {
    id: "continuum",
    title: "Continuum, OA, and PDE layer",
    subtitle: "How the finite orbit picture becomes a measure flow",
    thesis:
      "The same Mobius action pushes forward probability measures. The OA manifold is the orbit of the uniform boundary measure, governed by a continuity equation and a hyperbolic Poisson kernel.",
    accent: "#15803d",
    x: 930,
    y: 570,
    w: 520,
    h: 430,
    nodes: [
      {
        id: "measure-action",
        label: "Measure pushforward",
        short:
          "Particles become probability measures on the sphere and the Mobius group acts by pushforward.",
        formula: "rho -> g_* rho",
        status: "LMS theorem",
        source: "LMS.tex, Continuum limit",
        x: 24,
        y: 72,
        w: 220,
        h: 72,
      },
      {
        id: "continuity-pde",
        label: "Continuity PDE",
        short:
          "The continuum Kuramoto model is a transport equation driven by the same conformal vector field.",
        formula: "partial_t rho + div_S(rho v[rho])=0",
        status: "bridge",
        source: "LMS.tex plus PDE formulation",
        x: 276,
        y: 72,
        w: 220,
        h: 72,
      },
      {
        id: "oa-manifold",
        label: "OA / Poisson orbit",
        short:
          "The orbit G sigma of the uniform measure is d-dimensional because rotations stabilize sigma.",
        formula: "rho_z=(M_{-z})_* sigma",
        status: "LMS theorem",
        source: "LMS.tex, Continuum limit",
        x: 24,
        y: 176,
        w: 220,
        h: 72,
      },
      {
        id: "hyperbolic-poisson",
        label: "Hyperbolic Poisson kernel",
        short:
          "The OA densities in real dimension d use the hyperbolic, not Euclidean, Poisson kernel.",
        formula: "P_hyp(z,x)=((1-|z|^2)/|z-x|^2)^{d-1}",
        status: "LMS theorem",
        source: "LMS.tex, Continuum limit",
        x: 276,
        y: 176,
        w: 220,
        h: 72,
      },
      {
        id: "centroid-gap",
        label: "Centroid closure gap",
        short:
          "For d>=3, centroid radius is not simply z; the exact finite-N inverse must not depend on a first-moment closure.",
        formula: "Z(z)=K h_d(|z|^2) z, not always Kz",
        status: "LMS theorem",
        source: "LMS.tex, Eq. Zevaluated",
        x: 24,
        y: 280,
        w: 220,
        h: 72,
      },
      {
        id: "empirical-limit",
        label: "Empirical-to-continuum limit",
        short:
          "The exact finite-N potential is the empirical discretization of a Busemann functional on boundary measures.",
        formula: "Phi_mu(v)=int log((1-|v|^2)/|v-x|^2) dmu(x)",
        status: "bridge",
        source: "Synthesis from both notes",
        x: 276,
        y: 280,
        w: 220,
        h: 72,
      },
    ],
  },
  {
    id: "geometry",
    title: "Geometric research bridges",
    subtitle: "Frameworks that organize future questions",
    thesis:
      "Busemann inversion is a conformal barycenter problem on the boundary measure. OT, moment-map, and PDE language clarify what is exact, what is projected, and what should converge.",
    accent: "#be123c",
    x: 1530,
    y: 570,
    w: 500,
    h: 430,
    nodes: [
      {
        id: "conformal-barycenter",
        label: "Conformal barycenter",
        short:
          "The center v_* is the hyperbolic barycenter selected by vanishing average boundary boost.",
        formula: "int M_v(x) dmu(x)=0",
        status: "bridge",
        source: "Synthesis: Busemann center",
        x: 24,
        y: 72,
        w: 210,
        h: 72,
      },
      {
        id: "moment-map",
        label: "Moment-map reading",
        short:
          "The centered-slice equation is a zero level of the first moment after the group action.",
        formula: "J(g_*mu)=int x d(g_*mu)=0",
        status: "bridge",
        source: "Synthesis: symplectic/geometric analogy",
        x: 260,
        y: 72,
        w: 210,
        h: 72,
      },
      {
        id: "ot-orbit-projection",
        label: "Orbit projection",
        short:
          "Radius control is a projection inside the finite-dimensional Mobius orbit, not an arbitrary transport of particles.",
        formula: "mu -> (M_{w_target})_* p",
        status: "bridge",
        source: "Exact inversion note, reframed",
        x: 24,
        y: 176,
        w: 210,
        h: 72,
      },
      {
        id: "ot-metric-question",
        label: "OT metric question",
        short:
          "A natural next problem is to compare Busemann projection with Wasserstein geodesic projection on boundary measures.",
        formula: "min over g in G? W_2(g_*mu, S_0)",
        status: "bridge",
        source: "New synthesis",
        x: 260,
        y: 176,
        w: 210,
        h: 72,
      },
      {
        id: "ws-constants",
        label: "WS constants in d>2",
        short:
          "After canonical centering, Gram and moment invariants replace circle cross-ratios.",
        formula: "d=2 cross-ratios; d>2 Gram/moments",
        status: "bridge",
        source: "Gauge invariants draft, Sec. 7",
        x: 24,
        y: 280,
        w: 210,
        h: 72,
      },
      {
        id: "gradient-stability",
        label: "Boundary stability logic",
        short:
          "LMS stability, inversion uniqueness, and source exponents are the same potential geometry viewed in forward, inverse, and local forms.",
        formula: "Phi -> unique interior source -> boundary synchrony",
        status: "bridge",
        source: "Synthesis from LMS and notes",
        x: 260,
        y: 280,
        w: 210,
        h: 72,
      },
    ],
  },
];

const edges: Edge[] = [
  { from: "sphere-flow", to: "mobius-boosts", label: "infinitesimal generators", kind: "foundation" },
  { from: "mobius-boosts", to: "group-orbit", label: "builds Gp", kind: "foundation" },
  { from: "group-orbit", to: "reduced-odes", label: "coordinates", kind: "foundation" },
  { from: "reduced-odes", to: "linear-decoupling", label: "linear Z", kind: "foundation" },
  { from: "linear-decoupling", to: "lms-potential", label: "gradient identity", kind: "foundation" },
  { from: "gauge-dependence", to: "centered-slice", label: "fix boost gauge", kind: "exact" },
  { from: "empirical-cloud", to: "residual-equation", label: "full-cloud equation", kind: "exact" },
  { from: "centered-slice", to: "residual-equation", label: "zero barycenter", kind: "exact" },
  { from: "lms-potential", to: "cloud-potential", label: "replace anchors p by x", kind: "exact" },
  { from: "cloud-potential", to: "residual-equation", label: "critical iff R=0", kind: "exact" },
  { from: "lms-potential", to: "unique-center", label: "LMS uniqueness proof", kind: "exact" },
  { from: "residual-equation", to: "unique-center", label: "one inverse center", kind: "exact" },
  { from: "unique-center", to: "mobius-equivariance", label: "canonical", kind: "exact" },
  { from: "unique-center", to: "sign-clean", label: "choose v=-w", kind: "exact" },
  { from: "sign-clean", to: "deboosted-base", label: "recover p", kind: "exact" },
  { from: "local-initializer", to: "rapidity-solver", label: "seed optimizer", kind: "algorithm" },
  { from: "rapidity-solver", to: "unique-center", label: "numerical critical point", kind: "algorithm" },
  { from: "deboosted-base", to: "orbit-projection", label: "same orbit", kind: "algorithm" },
  { from: "deboosted-base", to: "finite-reconstruction", label: "stored constants", kind: "algorithm" },
  { from: "reduced-odes", to: "finite-reconstruction", label: "evolve low-dimensional state", kind: "foundation" },
  { from: "finite-reconstruction", to: "moving-frame", label: "deboost each time", kind: "invariant" },
  { from: "moving-frame", to: "covariant-constant", label: "canonical theorem", kind: "invariant" },
  { from: "covariant-constant", to: "gram-invariants", label: "rotational invariants", kind: "invariant" },
  { from: "covariant-constant", to: "moment-invariants", label: "tensor covariance", kind: "invariant" },
  { from: "reduced-odes", to: "connection", label: "rotation equation", kind: "invariant" },
  { from: "connection", to: "data-diagnostics", label: "estimate/check", kind: "invariant" },
  { from: "moment-invariants", to: "local-source", label: "inertia controls linearization", kind: "invariant" },
  { from: "lms-potential", to: "euler-sundman", label: "time rescaling", kind: "invariant" },
  { from: "group-orbit", to: "measure-action", label: "N -> measure", kind: "bridge" },
  { from: "sphere-flow", to: "continuity-pde", label: "transport limit", kind: "bridge" },
  { from: "measure-action", to: "oa-manifold", label: "orbit of uniform measure", kind: "foundation" },
  { from: "oa-manifold", to: "hyperbolic-poisson", label: "density formula", kind: "foundation" },
  { from: "hyperbolic-poisson", to: "centroid-gap", label: "d>=3 correction", kind: "foundation" },
  { from: "cloud-potential", to: "empirical-limit", label: "empirical integral", kind: "bridge" },
  { from: "empirical-limit", to: "conformal-barycenter", label: "boundary barycenter", kind: "bridge" },
  { from: "centered-slice", to: "moment-map", label: "zero moment", kind: "bridge" },
  { from: "orbit-projection", to: "ot-orbit-projection", label: "finite-dimensional projection", kind: "bridge" },
  { from: "ot-orbit-projection", to: "ot-metric-question", label: "compare with W_2", kind: "bridge" },
  { from: "gram-invariants", to: "ws-constants", label: "higher-dimensional WS constants", kind: "bridge" },
  { from: "moment-invariants", to: "ws-constants", label: "shape signatures", kind: "bridge" },
  { from: "lms-potential", to: "gradient-stability", label: "same potential", kind: "bridge" },
  { from: "unique-center", to: "gradient-stability", label: "inverse uniqueness", kind: "bridge" },
  { from: "local-source", to: "gradient-stability", label: "local fixed point structure", kind: "bridge" },
];

const relationLabels: Record<RelationKind, string> = {
  foundation: "LMS foundations",
  exact: "Exact inverse",
  algorithm: "Algorithms",
  invariant: "Invariants",
  bridge: "Research bridges",
};

const relationColors: Record<RelationKind, string> = {
  foundation: "#2563eb",
  exact: "#0f766e",
  algorithm: "#c2410c",
  invariant: "#9333ea",
  bridge: "#be123c",
};

const statusClass: Record<NodeStatus, string> = {
  "LMS theorem": "status-blue",
  "proved extension": "status-green",
  algorithm: "status-orange",
  diagnostic: "status-purple",
  bridge: "status-red",
};

function buildNodes() {
  const all = new Map<string, GraphNode>();
  for (const cluster of clusters) {
    for (const node of cluster.nodes) {
      all.set(node.id, {
        ...node,
        clusterId: cluster.id,
        clusterTitle: cluster.title,
        absX: cluster.x + node.x,
        absY: cluster.y + node.y,
      });
    }
  }
  return all;
}

function nodeCenter(node: GraphNode) {
  return {
    x: node.absX + node.w / 2,
    y: node.absY + node.h / 2,
  };
}

function edgePath(from: GraphNode, to: GraphNode) {
  const a = nodeCenter(from);
  const b = nodeCenter(to);
  const dx = b.x - a.x;
  const dy = b.y - a.y;
  const curve = Math.max(-90, Math.min(90, dx * 0.08));
  const c1x = a.x + dx * 0.45;
  const c1y = a.y + dy * 0.2 + curve;
  const c2x = a.x + dx * 0.55;
  const c2y = a.y + dy * 0.8 - curve;
  return `M ${a.x} ${a.y} C ${c1x} ${c1y}, ${c2x} ${c2y}, ${b.x} ${b.y}`;
}

function edgeLabelPosition(from: GraphNode, to: GraphNode) {
  const a = nodeCenter(from);
  const b = nodeCenter(to);
  return {
    x: (a.x + b.x) / 2,
    y: (a.y + b.y) / 2,
  };
}

function matchesSearch(node: GraphNode, search: string) {
  if (!search.trim()) return true;
  const needle = search.toLowerCase();
  return [node.label, node.short, node.formula, node.source, node.clusterTitle]
    .filter(Boolean)
    .some((value) => value!.toLowerCase().includes(needle));
}

export default function GraphClient() {
  const nodeMap = useMemo(() => buildNodes(), []);
  const [selectedId, setSelectedId] = useState("unique-center");
  const [activeKinds, setActiveKinds] = useState<Set<RelationKind>>(
    () => new Set(["foundation", "exact", "algorithm", "invariant", "bridge"]),
  );
  const [search, setSearch] = useState("");
  const [zoom, setZoom] = useState(1.2);
  const [pan, setPan] = useState({ x: -50, y: -45 });
  const [dragStart, setDragStart] = useState<null | {
    pointerX: number;
    pointerY: number;
    panX: number;
    panY: number;
  }>(null);

  const selected = nodeMap.get(selectedId) ?? nodeMap.get("unique-center")!;
  const connectedIds = useMemo(() => {
    const ids = new Set<string>([selected.id]);
    for (const edge of edges) {
      if (edge.from === selected.id) ids.add(edge.to);
      if (edge.to === selected.id) ids.add(edge.from);
    }
    return ids;
  }, [selected.id]);

  const visibleEdges = edges.filter((edge) => activeKinds.has(edge.kind));
  const filteredNodeIds = useMemo(() => {
    const ids = new Set<string>();
    for (const node of nodeMap.values()) {
      if (matchesSearch(node, search)) ids.add(node.id);
    }
    return ids;
  }, [nodeMap, search]);

  const selectedIncoming = edges.filter((edge) => edge.to === selected.id);
  const selectedOutgoing = edges.filter((edge) => edge.from === selected.id);

  function toggleKind(kind: RelationKind) {
    setActiveKinds((previous) => {
      const next = new Set(previous);
      if (next.has(kind)) {
        next.delete(kind);
      } else {
        next.add(kind);
      }
      return next;
    });
  }

  function fitAll() {
    setZoom(0.64);
    setPan({ x: 18, y: 10 });
  }

  function focusCluster(clusterId: string) {
    const cluster = clusters.find((item) => item.id === clusterId);
    if (!cluster) return;
    setZoom(0.96);
    setPan({ x: 320 - cluster.x * 0.96, y: 110 - cluster.y * 0.96 });
    setSelectedId(cluster.nodes[0].id);
  }

  return (
    <main className="app-shell">
      <section className="graph-workspace" aria-label="Interactive LMS framework graph">
        <div className="toolbar">
          <div className="title-block">
            <p className="eyebrow">Kuramoto on the sphere</p>
            <h1>LMS exact-gauge framework map</h1>
          </div>
          <div className="toolbar-controls">
            <label className="search-label">
              <span>Search</span>
              <input
                value={search}
                onChange={(event) => setSearch(event.target.value)}
                placeholder="Busemann, Gram, OA, radius..."
              />
            </label>
            <select
              aria-label="Focus cluster"
              onChange={(event) => focusCluster(event.target.value)}
              defaultValue=""
            >
              <option value="" disabled>
                Focus cluster
              </option>
              {clusters.map((cluster) => (
                <option key={cluster.id} value={cluster.id}>
                  {cluster.title}
                </option>
              ))}
            </select>
            <button type="button" onClick={() => setZoom((value) => Math.min(1.72, value + 0.08))}>
              Zoom in
            </button>
            <button type="button" onClick={() => setZoom((value) => Math.max(0.42, value - 0.08))}>
              Zoom out
            </button>
            <button type="button" onClick={fitAll}>
              Fit
            </button>
          </div>
        </div>

        <div className="relation-strip" aria-label="Relation filters">
          {(Object.keys(relationLabels) as RelationKind[]).map((kind) => (
            <button
              key={kind}
              type="button"
              className={activeKinds.has(kind) ? "filter active" : "filter"}
              style={{ "--filter-color": relationColors[kind] } as CSSProperties}
              onClick={() => toggleKind(kind)}
            >
              {relationLabels[kind]}
            </button>
          ))}
        </div>

        <div className="graph-frame">
          <svg
            className="graph-svg"
            viewBox="0 0 2100 1080"
            role="img"
            aria-label="Interlinked diagram of LMS, exact Busemann inversion, invariants, continuum limits, and geometric bridges"
            onPointerDown={(event) => {
              if ((event.target as Element).closest("[data-node]")) return;
              setDragStart({
                pointerX: event.clientX,
                pointerY: event.clientY,
                panX: pan.x,
                panY: pan.y,
              });
            }}
            onPointerMove={(event) => {
              if (!dragStart) return;
              setPan({
                x: dragStart.panX + event.clientX - dragStart.pointerX,
                y: dragStart.panY + event.clientY - dragStart.pointerY,
              });
            }}
            onPointerUp={() => setDragStart(null)}
            onPointerLeave={() => setDragStart(null)}
          >
            <defs>
              {(Object.keys(relationColors) as RelationKind[]).map((kind) => (
                <marker
                  key={kind}
                  id={`arrow-${kind}`}
                  viewBox="0 0 10 10"
                  refX="9"
                  refY="5"
                  markerWidth="7"
                  markerHeight="7"
                  orient="auto-start-reverse"
                >
                  <path d="M 0 0 L 10 5 L 0 10 z" fill={relationColors[kind]} />
                </marker>
              ))}
            </defs>
            <g transform={`translate(${pan.x} ${pan.y}) scale(${zoom})`}>
              <g className="edges">
                {visibleEdges.map((edge, index) => {
                  const from = nodeMap.get(edge.from)!;
                  const to = nodeMap.get(edge.to)!;
                  const isSelected = edge.from === selected.id || edge.to === selected.id;
                  const searchHit = filteredNodeIds.has(edge.from) || filteredNodeIds.has(edge.to);
                  const label = edgeLabelPosition(from, to);
                  return (
                    <g
                      key={`${edge.from}-${edge.to}-${index}`}
                      className={[
                        "edge",
                        isSelected ? "edge-selected" : "",
                        search.trim() && !searchHit ? "edge-muted" : "",
                      ].join(" ")}
                    >
                      <path
                        d={edgePath(from, to)}
                        fill="none"
                        stroke={relationColors[edge.kind]}
                        strokeWidth={isSelected ? 3.2 : 1.8}
                        strokeOpacity={isSelected ? 0.86 : 0.34}
                        markerEnd={`url(#arrow-${edge.kind})`}
                      />
                      {(isSelected || zoom > 0.82) && (
                        <text
                          className="edge-label"
                          x={label.x}
                          y={label.y}
                          fill={relationColors[edge.kind]}
                        >
                          {edge.label}
                        </text>
                      )}
                    </g>
                  );
                })}
              </g>

              <g className="clusters">
                {clusters.map((cluster) => (
                  <g key={cluster.id}>
                    <rect
                      className="cluster-shell"
                      x={cluster.x}
                      y={cluster.y}
                      width={cluster.w}
                      height={cluster.h}
                      rx="8"
                      style={{ "--cluster-color": cluster.accent } as CSSProperties}
                    />
                    <rect
                      className="cluster-topline"
                      x={cluster.x}
                      y={cluster.y}
                      width={cluster.w}
                      height="8"
                      rx="4"
                      fill={cluster.accent}
                    />
                    <text className="cluster-title" x={cluster.x + 22} y={cluster.y + 34}>
                      {cluster.title}
                    </text>
                    <text className="cluster-subtitle" x={cluster.x + 22} y={cluster.y + 56}>
                      {cluster.subtitle}
                    </text>
                  </g>
                ))}
              </g>

              <g className="nodes">
                {[...nodeMap.values()].map((node) => {
                  const cluster = clusters.find((item) => item.id === node.clusterId)!;
                  const isSelected = selected.id === node.id;
                  const isConnected = connectedIds.has(node.id);
                  const isSearchHit = filteredNodeIds.has(node.id);
                  const muted = (search.trim() && !isSearchHit) || (!isConnected && selected.id !== node.id);
                  return (
                    <g
                      key={node.id}
                      data-node={node.id}
                      className={[
                        "node",
                        isSelected ? "node-selected" : "",
                        isConnected ? "node-connected" : "",
                        muted ? "node-muted" : "",
                      ].join(" ")}
                      transform={`translate(${node.absX} ${node.absY})`}
                      onClick={() => setSelectedId(node.id)}
                      tabIndex={0}
                      role="button"
                      aria-label={`Select ${node.label}`}
                      onKeyDown={(event) => {
                        if (event.key === "Enter" || event.key === " ") setSelectedId(node.id);
                      }}
                    >
                      <rect
                        width={node.w}
                        height={node.h}
                        rx="8"
                        fill="#ffffff"
                        stroke={isSelected ? cluster.accent : "#cbd5e1"}
                        strokeWidth={isSelected ? 3 : 1.2}
                      />
                      <rect width="7" height={node.h} rx="4" fill={cluster.accent} />
                      <text className="node-title" x="18" y="22">
                        {node.label}
                      </text>
                      <text className="node-short" x="18" y="44">
                        {node.short.length > 54 ? `${node.short.slice(0, 54)}...` : node.short}
                      </text>
                      {node.formula && (
                        <text className="node-formula" x="18" y={node.h - 14}>
                          {node.formula.length > 44 ? `${node.formula.slice(0, 44)}...` : node.formula}
                        </text>
                      )}
                    </g>
                  );
                })}
              </g>
            </g>
          </svg>
        </div>
      </section>

      <aside className="detail-panel" aria-label="Selected idea detail">
        <div className="detail-header">
          <span className={`status-pill ${statusClass[selected.status]}`}>
            {selected.status}
          </span>
          <span className="source-pill">{selected.clusterTitle}</span>
        </div>
        <h2>{selected.label}</h2>
        <p className="detail-short">{selected.short}</p>
        {selected.formula && <pre className="formula-box">{selected.formula}</pre>}
        <dl className="detail-list">
          <dt>Source</dt>
          <dd>{selected.source}</dd>
          <dt>Mathematical role</dt>
          <dd>{clusters.find((cluster) => cluster.id === selected.clusterId)?.thesis}</dd>
        </dl>

        <div className="dependency-block">
          <h3>Incoming dependencies</h3>
          {selectedIncoming.length ? (
            selectedIncoming.map((edge) => (
              <button key={`${edge.from}-${edge.to}`} onClick={() => setSelectedId(edge.from)}>
                <span>{nodeMap.get(edge.from)?.label}</span>
                <strong>{edge.label}</strong>
              </button>
            ))
          ) : (
            <p>No incoming edge in this map.</p>
          )}
        </div>

        <div className="dependency-block">
          <h3>Outgoing consequences</h3>
          {selectedOutgoing.length ? (
            selectedOutgoing.map((edge) => (
              <button key={`${edge.from}-${edge.to}`} onClick={() => setSelectedId(edge.to)}>
                <span>{nodeMap.get(edge.to)?.label}</span>
                <strong>{edge.label}</strong>
              </button>
            ))
          ) : (
            <p>No outgoing edge in this map.</p>
          )}
        </div>

        <div className="legend-block">
          <h3>Reading guide</h3>
          <p>
            Blue dependencies are LMS foundations. Green dependencies are exact finite-N
            inverse-gauge statements. Orange nodes are operational algorithms. Purple
            links are moving-frame invariants and diagnostics. Red links are synthesis
            bridges to conformal barycenters, PDE limits, WS constants, and OT questions.
          </p>
        </div>
      </aside>
    </main>
  );
}
